# syntax=docker/dockerfile:1

FROM python:3.8

ARG PETFINDER_KEY
ARG PETFINDER_SECRET_KEY
ARG AWS_SECRET_ID
ARG AWS_SECRET_ACCESS_KEY
ARG DB_HOST
ARG DB_NAME
ARG DB_USER
ARG DB_PASSWORD

ENV PETFINDER_KEY=${PETFINDER_KEY}
ENV PETFINDER_SECRET_KEY=${PETFINDER_SECRET_KEY}
ENV AWS_SECRET_ID=${AWS_SECRET_ID}
ENV AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
ENV DB_HOST=${DB_HOST}
ENV DB_NAME=${DB_NAME}
ENV DB_USER=${DB_USER}
ENV DB_PASSWORD=${DB_PASSWORD}

COPY . .

RUN pip3 install -r requirements.txt
RUN pip3 install wheel python-dotenv
RUN python setup.py sdist bdist_wheel
RUN pip3 install dist/pethub-0.0.1-py3-none-any.whl

CMD ["python", "pethub/petfinder/main.py"]
